// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vccemcmnyqdpntcoxasg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZjY2VtY21ueXFkcG50Y294YXNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxMjY4MjEsImV4cCI6MjA2NzcwMjgyMX0.6PZiamwdl-E2ttMFpM0qhDk93zr-U6C-CB3yYrSz8R8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});